import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navigation } from "@/components/nav/bottomnav";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} font-pretendard antialiased flex justify-center bg-gray-100`}>
        <div className="flex flex-col w-full max-w-[500px] min-h-dvh max-h-dvh bg-white relative shadow-2xl shadow-neutral-200">
          <div className="flex-1 overflow-auto w-full">{children}</div>
          <Navigation />
        </div>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
