import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "@/components/nav/bottomnav";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${pretendard.variable} font-pretendard antialiased flex justify-center bg-gray-100 overflow-auto`}>
        <div className="min-h-screen w-full mx-auto max-w-[600px] bg-white shadow-2xl shadow-neutral-200 relative">
          <div className="pb-16 h-full">{children}</div>
          <Navigation />
        </div>

        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
